#Eje1
numero1=4
#ejer2 
numero2=2.4
#ejer3 
suma=numero1+numero2
#ejer4
resta=numero1-numero2
mul=numero1*numero2
div=numero1/numero2
#ejer5
nombre="Maximiliano"
#ejer6
precio=23.50
#ejer7
descuento=0.33
#ejer8
precio_final=precio-(precio*descuento)
#ejer9
cadena="hola mundo"
#ejer10
longitud=len(cadena)
#ejer11
precio2=5.25
precio2=int(precio2)

#ejer12
nombre2="Maximiliano"
apelido="Herrera"
nombreapellido=nombre2+apelido
print(nombreapellido)